dirs:
  - .
modifiedFilesOnly: true
# Ignore links for setup dev environment
ignorePatterns:
  - pattern: '^http://localhost(.*)'
  - pattern: '^(.*).loc/$'
# Remove gitlab anchors to lines to prevent linkspector to write to stderr for github-action to work
replacementPatterns:
  - pattern: "^(.*)#(L\\d+)$"
    replacement: '$1'
